import { CategoriaProducto, Estado, IProducto } from "./models";

export const productosIniciales: IProducto[] = [
    {
        id: 1,
        codigo: 'FR001',
        nombre: 'Manzanas Fuji',
        descripcion: 'Manzanas Fuji crujientes y dulces, cultivadas en el Valle del Maule. Perfectas para meriendas saludables o como ingrediente en postres.',
        precio: 1200,
        stock: 150,
        imagen: 'img/manzanas.webp',
        categoria: CategoriaProducto.frutas,
        isActivo: Estado.activo,
        fechaCreacion: '2024-01-01',
        peso: '1kg',
    },
    {
        id: 2,
        codigo: 'FR002',
        nombre: 'Naranjas Valencia',
        descripcion: 'Jugosas y ricas en vitamina C, ideales para zumos frescos y refrescantes. Cultivadas en condiciones climáticas óptimas.',
        precio: 1000,
        stock: 200,
        imagen: 'img/naranja.webp',
        categoria: CategoriaProducto.frutas,
        isActivo: Estado.activo,
        fechaCreacion: '2024-01-02',
        peso: '1kg',
    },
    {
        id: 3,
        codigo: 'VR001',
        nombre: 'Zanahorias Orgánicas',
        descripcion: 'Zanahorias crujientes cultivadas sin pesticidas en la Región de O\'Higgins. Excelente fuente de vitamina A y fibra.',
        precio: 900,
        stock: 100,
        imagen: 'img/zanahorias.webp',
        categoria: CategoriaProducto.verduras,
        isActivo: Estado.activo,
        fechaCreacion: '2024-01-03',
        peso: '1kg',
    },
    {
        id: 4,
        codigo: 'PO001',
        nombre: 'Miel Orgánica',
        descripcion: 'Miel pura y orgánica producida por apicultores locales. Rica en antioxidantes y con un sabor inigualable.',
        precio: 5000,
        stock: 50,
        imagen: 'img/miel.webp',
        categoria: CategoriaProducto.organicos,
        isActivo: Estado.activo,
        fechaCreacion: '2024-01-04',
        peso: '500g',
    },
    {
        id: 5,
        codigo: 'PL001',
        nombre: 'Leche Entera',
        descripcion: 'Producto lácteo proveniente de granjas locales que se dedican a la producción responsable y de calidad. Rica en calcio y nutrientes.',
        precio: 1800,
        stock: 100,
        imagen: 'img/default.jpg', // Imagen por defecto
        categoria: CategoriaProducto.lacteos,
        isActivo: Estado.activo,
        fechaCreacion: '2024-01-05',
        peso: '1L',
    },
];